Circuit breaking toegevoegd.
digipolisantwerpdocumentation/api-design-and-patterns pull request #1
Opened 2018-04-10 12:55 UTC by StevenVandenBroeck

2018-04-16 13:12 UTC, PeterClaes commented on README.md
> +> Circuit breaking vermijdt onnodig gebruik van resources door requests die niet gaan lukken onmiddelijk te doen falen ipv ze uit te voeren.
.. door requests die **(eventueel tijdelijk)** niet gaan lukken, onmiddel**l**ijk ...

2018-04-16 13:17 UTC, PeterClaes commented on implementaties/circuit-breaking-implementatie.md
> +De circuit breaker registreert de communicatiefouten naar de service. Wanneer een vooraf bepaald threshold van aantal mislukte communicaties binnen een tijdspanne bereikt is, zet de circuit breaker z
... vooraf bepaalde ...

2018-04-16 13:24 UTC, PeterClaes commented on terminologie.md
> +| API      | Een programma interface bestaande uit 1 of meerdere endpoints die een request-response gebaseerde communicatie aanbieden naar een functionaliteit. |
tabel wordt niet correct gevisualiseerd

2018-04-16 13:30 UTC, PeterClaes requested changes
zie comments

2018-04-17 12:00 UTC, StevenVandenBroeck commented on README.md
> +> Circuit breaking vermijdt onnodig gebruik van resources door requests die niet gaan lukken onmiddelijk te doen falen ipv ze uit te voeren.
(eventueel tijdelijk) had ik er uit gelaten omdat ik al gemerkt hebt dat zo'n dingen het veel moeilijker leesbaar en begrijpbaar maken.

2018-04-17 12:18 UTC, tom-dierckx requested changes

2018-04-17 12:18 UTC, tom-dierckx commented on terminologie.md
> +| API      | Een programma interface bestaande uit 1 of meerdere endpoints die een request-response gebaseerde communicatie aanbieden naar een functionaliteit. |
Rendering werkt niet voor tabels zonder header.
Voorstel:
|Term| Verduidelijking |
|----|---|
| API      | Een programma interface bestaande uit 1 of meerdere endpoints die een request-response gebaseerde communicatie aanbieden naar een functionaliteit. |
| Endpoint | 1 vd 2 kanten van een communicatie, meestal gedefinieerd door een URL.                                                                             |

2018-04-19 20:27 UTC, PeterClaes commented on README.md
> +> Circuit breaking vermijdt onnodig gebruik van resources door requests die niet gaan lukken onmiddelijk te doen falen ipv ze uit te voeren.
OK

2018-06-01 07:48 UTC, PeterClaes approved these changes

2018-06-01 07:49 UTC, merged