Multitenancy
digipolisantwerpdocumentation/api-design-and-patterns pull request #2
Opened 2018-04-18 08:05 UTC by Gijs1

Graag revisie, maar ook pushen naar master branch wegens dringende vraag.

2018-04-18 12:20 UTC, tom-dierckx requested changes

2018-04-18 12:20 UTC, tom-dierckx commented on patterns/multitenancy.md
> +  * Een fictief voorbeeld met 3 tenants:
Is een UME beschrijving wel van toepassing in een api-design-and-patterns document?

2018-04-18 12:20 UTC, tom-dierckx commented on patterns/multitenancy.md
> +* Formaat: UUID met 36 tekens,  waarvan 32 hexadecimale karakters en vier streepjes: 8-4-4-4-12
RFC rond UUID's misschien vermelden => https://tools.ietf.org/html/rfc4122 + de keuze van versie (versie 4 lijkt mij een goede keuze)

2018-04-18 12:20 UTC, tom-dierckx commented on patterns/multitenancy.md
> +Neen, de unieke tenant id’s worden bewaard door de provider component zelf, niet centraal. Dit kan bijvoorbeeld in een tabel in de 'tenant catalog' databank.
'tenant catalog' is een table in de 'administration' databank van de engine?

2018-06-01 07:54 UTC, PeterClaes commented on patterns/multitenancy.md
> +| Tenant catalog | Een component draagt zelf de verantwoordelijkheid voor persistentie van de tenant id’s, dit geldt voor de provider of consumer kant, of beide. De persistentie gebeurd in de zogenaa
de persistentie gebeur-t- in  ....

2018-06-01 07:56 UTC, PeterClaes commented on patterns/multitenancy.md
> +* Elke (nieuwe) (ACPaaS) component wordt verwacht rekening te houden met multi-tenancy, hetzij in de hoedanigheid van provider of als consumer.
hetzij als provider, hetzij als consumer .

2018-06-01 07:59 UTC, PeterClaes commented on patterns/multitenancy.md
> +De provider componenten zelf zijn verantwoordelijk voor tenant beheer en persistentie. In de praktijk 1 of meerdere tenants. Elke tenant heeft  een uniek tenant id.
... zijn zelf verantwoordelijk ... In de praktijk heeft men altijd 1 of meerder tenants.

2018-06-01 09:39 UTC, PeterClaes commented on patterns/multitenancy.md
> +* Bij aanvraag van rollen in de UME kan men tenants onderscheiden dmv de organisatie gedeelte op te splitsen per tenant in  het volgende patroon: “G_TPS_Organisatie_Applicatie_NaamvdRol".
Ik zou UME zaken niet vermelden. Staat los van multi-tenancy. En anders ga je ook UME moten uitleggen.

2018-06-01 09:57 UTC, PeterClaes commented on patterns/multitenancy.md
> +* Bij aanroep van een bedrijfsmethode geeft de consumer component de tenant id mee in de HTTP header.  Deze tenant id moet gekend zijn in de tenant provider die wordt aangeroepen.
... geeft de consumer component de tenant id (dgp-tenant-id) mee in  ...

2018-06-01 10:02 UTC, PeterClaes commented on patterns/multitenancy.md
> +* De component kan op basis van de UME rollen/permissies de verschillende tenants van een geauthenticeerde gebruiker bepalen.
vermijd UME. vermeld gewoon rollen/permissies

2018-06-01 10:03 UTC, PeterClaes commented on patterns/multitenancy.md
> +* De gebruiker maakt een keuze en start feitelijk een sessie met voor één specifieke tenant.
.. en start feitelijk een sessie voor één specifieke tenant.

2018-06-01 10:04 UTC, PeterClaes commented on patterns/multitenancy.md
> +* De toepassing linkt de gebruiker dus aan specifieke tenant om vb. de correcte databank aan te spreken.
Ik zou datastore gebruiken ipv databank

2018-06-01 10:04 UTC, PeterClaes commented on patterns/multitenancy.md
> +##### Wat met gemeenschappelijke data in de databanken?
Ik zou datastore gebruiken ipv databank

2018-06-01 10:08 UTC, PeterClaes requested changes
zie comments

2018-06-01 10:08 UTC, PeterClaes commented on patterns/multitenancy.md
> +Iedere tenant heeft zijn eigen databank(schema). De tenant catalog bevat data nodig voor het tenant beheer van de component. De tenant catalog bevindt zich op zijn beurt in een eigen databank(schema)
Ik zou datastore gebruiken ipv databank

2018-06-27 10:00 UTC, merged